server:
  port: 8080

spring:
  datasource:
    username: root
    password: sa123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    minIdle: 5
    initialSize: 5
    maxActive: 20

#    filters: stat
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20


#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  mapper-locations: classpath*:com.pazz.springboot.mybatis.dao
#  type-aliases-package: com.pazz.springboot.mybatis.entity